name: Node CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download and configure Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
