name: Node CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Node.js CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
